### PR TITLE
Voting members

### PR DESCRIPTION
**Pull request by wjf136**
@tmackenzie Ready for review

### CODE REVIEW

**Comment by tmackenzie** [comment]
👍

**Comment by wjf136** [comment]
I see 2 split votes and the PR was closed? Not even abiding by your own 2/3 majority rule... unbelievable
...just...
...unbelievable...

**Comment by philmadden83** [comment]
I thought you also needed to be a full time employee..

**Comment by fawaad** [comment]
Oh hey, I still have access to this repo! Who isn't an employee anymore?

**Comment by artisanpixel** [comment]
@fawaad --- quick - delete the repo!

**Pull request closed without merging**
